# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-08-01 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flightleg',
            unique_together=set([('departure', 'arrival', 'origin', 'destination')]),
        ),
    ]
