# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-08-22 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230801_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('choice_text', 'votes')]),
        ),
    ]
