# Generated by Django 4.2.14 on 2025-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_article_id_alter_choice_id_alter_flight_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
