# Generated by Django 4.2.14 on 2025-09-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='name1',
        ),
    ]
