# Generated by Django 4.2.14 on 2025-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_name_article_name1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('title_en',)},
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(default='en', max_length=30, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title_kk',
            field=models.CharField(default='kk', max_length=30, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(default='ru', max_length=30, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('title_en', 'create_date')},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
    ]
