# Generated by Django 4.2.14 on 2025-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set(),
        ),
    ]
